### ISSUE TITLE
[BE]create new table for skills{id, name of the skills}, add 20 real skills and rename our current table to graduate-skills

### ISSUE THREAD

**Issue by kavitappatil** [simeonbikov/future-hire#44]
## Story

- **As a** developer 

- **I Want** to create a new table for skills, add 20 real skills and  rename our current table to graduate-skills

- **So That** we can retrieve the data easily. 

## Acceptance Criteria

1. Given I am a developer
   - When I view a database 
   - Then I should see three tables Graduates, Graduate-skills and skills.
2. Given  I am a developer
   - When  I view a skills table 
   - Then I should see real programming skills.
   

// /graduates GET
[{id: 1, name: "Bob", skills: [{id: 1, name: "React"}, {id: 3, "JavaScript"}]}]

// /graduate:id GET
{id: 1, name: "Bob", skills: [{id: 1, name: "React"}, {id: 3, "JavaScript"}, summary: "I have 6 months experience in React"]}

// /skills GET
[{id: 1, name: "React"}, {id: 2, "CSS"}, {id: 3, "JavaScript"}]

**Comment by FranklinPTorres** [comment]
Hi Guys my task is done, I modified our current table "skills"  to ==> graduate_skills and I created a new table named "skills" with the data "id" and "skills", with 20 programming language skills.

**Comment by kavitappatil** [comment]
Hi Franklin, can you push the changes in the branch, I cannot see your changes in the branch.

**Comment by simeonbikov** [comment]
Table graduate_skills is not ready. 
![image](https://user-images.githubusercontent.com/105053447/221438264-1adcb9f9-ece1-49d2-921f-2f414b8b7f6c.png)

**Comment by FranklinPTorres** [comment]
You are right simeon, I forgot that, that is not on the issue label, I will modify that ASAP
